### ISSUE TITLE
Components missing from BOMs

### ISSUE THREAD

**Issue by glbyers** [DigitalArtDeco/SwitchModePSUinTO3#2]
It is not specified in either the 12V or 5V BOMs what the values of cin2, cout2 & cout3 should be. There isn't any schematic, so no way to confirm. Should these be;

cin1=cin2
cout1=cout2=cout3?

Likewise, there is no mention of the purpose of rv1, although it appears it may be optional?

Thanks

**Comment by DigitalArtDeco** [comment]
Hello, unfortunately I did not notice that the values are missing. Now I have updated the BOM files. You do not need the component RV1! It is optional and used for a potentiometer to get an adjustable controller. Just leave the RV1 free! BR

**Comment by glbyers** [comment]
Excellent. Thank you!
